# Generated by Django 4.0.3 on 2022-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=30)),
            ],
        ),
    ]
