# Generated by Django 4.0.3 on 2022-05-21 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0006_alter_productos_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.TextField(max_length=30)),
                ('tipo_doc', models.CharField(max_length=30)),
                ('num_doc', models.IntegerField(default=0)),
                ('correo', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=30)),
                ('depto', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(max_length=30)),
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos')),
            ],
        ),
    ]
