# Generated by Django 4.0.3 on 2022-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
