# Generated by Django 4.0.3 on 2022-05-24 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_productos_imagen'),
        ('ventas', '0002_venta_total_venta_alter_venta_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.productos'),
        ),
    ]
